agent: 'sac'

#common
id: 'docking'
device: 'cuda'
seed: 1

#environment specific
target: 'fa7'
selfies_enc_type: 'one_hot'
max_selfie_length: 22
vina_program: 'qvina2'
temp_dir: 'tmp'
exhaustiveness: 1
num_sub_proc: 12
num_cpu_dock: 1
num_modes: 10
timeout_gen3d: 30
timeout_dock: 100

#data
num_train_steps: 1000000
env_buffer_size: 100000

explore_molecules: 250
parallel_molecules: 250
batch_size: 256
obs_dtype:
action_dtype:

#learning
gamma: 0.99
tau: 0.01
target_update_interval: 1
policy_update_interval: 2
lr: {'encoder':3e-4, 'actor':3e-4, 'critic':1e-3, 'alpha':1e-3}

#exploration
entropy_coefficient: 0.1

#hidden_dims and layers
hidden_dims: 256
latent_dims: 32

#evaluation
eval_episode_interval: 10000
num_eval_episodes: 5

#logging
wandb_log: False
wandb_entity: 'raj19'
wandb_run_name: 'sac-disc'
agent_log_interval: 100

#saving
save_snapshot: False
save_snapshot_interval: 100000

hydra:
  run:
    dir: ./local_exp/${now:%Y.%m.%d}/${now:%H.%M.%S}_${seed}
  job:
    chdir: False