#common
id: 'docking'
device: 'cuda'
seed: 1

#environment specific
target: 'fa7'
selfies_enc_type: 'index'
max_selfie_length: 22
vina_program: 'qvina2'
temp_dir: 'tmp'
exhaustiveness: 1
num_sub_proc: 12
num_cpu_dock: 1
num_modes: 10
timeout_gen3d: 30
timeout_dock: 100

#data
num_train_steps: 100000
env_buffer_size: 100000
explore_molecules: 250
parallel_molecules: 250
batch_size: 256
obs_dtype:
action_dtype:

#learning
lr: {'actor':1e-4, 'reward':1e-4, 'alpha':1e-3}
max_grad_norm: 0.5
vocab_size:
pad_idx:

#Actor
actor:
  _target_: mbac.Actor
  vocab_size: ${vocab_size}
  pad_idx: ${pad_idx}
  device: ${device}
  output_size: ${vocab_size}
  num_layers: 3
  hidden_size: 256
  embedding_size: 32

#Reward
reward:
  _target_: mbac.Reward
  vocab_size: ${vocab_size}
  pad_idx: ${pad_idx}
  device: ${device}
  num_layers: 3
  hidden_size: 256
  embedding_size: 32

#evaluation
eval_episode_interval: 10000
num_eval_episodes: 5 

#logging
wandb_log: False
wandb_entity: 'raj19'
wandb_run_name: 'mbac-disc'
agent_log_interval: 100

#saving
save_snapshot: False
save_snapshot_interval: 100000

hydra:
  run:
    dir: ./local_exp/${now:%Y.%m.%d}/${now:%H.%M.%S}_${seed}
  job:
    chdir: False